BACKEND_URL = "https://music-moodboard.onrender.com"
SPOTIFY_REDIRECT_URI="https://music-moodboard.onrender.com/callback"
SPOTIFY_CLIENT_ID="9c0b2779dd224fdbb6a9c5707a43155d"
SPOTIFY_CLIENT_SECRET="3768e2ebba2a4b4996505e0a1804d4ed"